// AUTO-GENERATED by scripts/build-snippet-data.ts. Do not edit by hand.
// Source files: packages/studio-fixtures/src/snippets/{starters,patterns}/*.yaml
// Inlined so studio-core consumers (Vite browser bundle) avoid runtime node:fs.

export const SNIPPET_DATA = {
  starters: {
    'archon-feature-development': `name: archon-feature-development
description: |
  Use when: Implementing a feature from an existing plan.
  Input: Path to a plan file ($ARTIFACTS_DIR/plan.md) or GitHub issue containing a plan.
  Does: Implements the plan with validation loops -> creates pull request.
  NOT for: Creating plans (plans should be created separately), bug fixes, code reviews.

nodes:
  - id: implement
    command: archon-implement
    model: opus[1m]

  - id: create-pr
    command: archon-create-pr
    depends_on: [implement]
    context: fresh

  - id: verify-pr-base
    bash: |
      set -euo pipefail
      EXPECTED="$BASE_BRANCH"
      ACTUAL=$(gh pr view --json baseRefName -q '.baseRefName')
      if [ "$ACTUAL" != "$EXPECTED" ]; then
        PR_NUMBER=$(gh pr view --json number -q '.number')
        echo "Base mismatch on PR #$PR_NUMBER: expected=$EXPECTED actual=$ACTUAL — re-targeting" >&2
        gh pr edit "$PR_NUMBER" --base "$EXPECTED"
      else
        echo "PR base verified: $EXPECTED"
      fi
    depends_on: [create-pr]
`,
    'archon-fix-github-issue': `name: archon-fix-github-issue
description: |
  Use when: User wants to FIX, RESOLVE, or IMPLEMENT a solution for a GitHub issue.
  Triggers: "fix this issue", "implement issue #123", "resolve this bug", "fix it",
            "fix issue", "resolve issue", "fix #123".
  NOT for: Comprehensive multi-agent reviews (use archon-issue-review-full),
           questions about issues, CI failures, PR reviews, general exploration.

  DAG workflow that:
  1. Classifies the issue (bug/feature/enhancement/etc)
  2. Researches context (web research + codebase exploration via investigate/plan)
  3. Routes to investigate (bugs) or plan (features) based on classification
  4. Implements the fix/feature with validation
  5. Creates a draft PR using the repo's PR template
  6. Runs smart review (always code review + CLAUDE.md check, conditional additional agents)
  7. Aggressively self-fixes all findings (tests, docs, error handling)
  8. Simplifies changed code (implements fixes directly, not just reports)
  9. Reports results back to the GitHub issue with follow-up suggestions

nodes:
  # ═══════════════════════════════════════════════════════════════
  # PHASE 1: FETCH & CLASSIFY
  # ═══════════════════════════════════════════════════════════════

  - id: extract-issue-number
    prompt: |
      Find the GitHub issue number for this request.

      Request: $ARGUMENTS

      Rules:
      - If the message contains an explicit issue number (e.g., "#709", "issue 709", "709"), extract that number.
      - If the message is ambiguous (e.g., "fix the SQLite timestamp bug"), use \`gh issue list\` to search for matching issues and pick the best match.

      CRITICAL: Your final output must be ONLY the bare number with no quotes, no markdown, no explanation. Example correct output: 709

  - id: fetch-issue
    bash: |
      # Strip quotes, whitespace, markdown backticks from AI output
      ISSUE_NUM=$(echo "$extract-issue-number.output" | tr -d "'\\"\\\`\\n " | grep -oE '[0-9]+' | head -1)
      if [ -z "$ISSUE_NUM" ]; then
        echo "Failed to extract issue number from: $extract-issue-number.output" >&2
        exit 1
      fi
      gh issue view "$ISSUE_NUM" --json title,body,labels,comments,state,url,author
    depends_on: [extract-issue-number]

  - id: classify
    prompt: |
      You are an issue classifier. Analyze the GitHub issue below and determine its type.

      ## Issue Content

      $fetch-issue.output

      ## Classification Rules

      | Type | Indicators |
      |------|------------|
      | bug | "broken", "error", "crash", "doesn't work", stack traces, regression |
      | feature | "add", "new", "support", "would be nice", net-new capability |
      | enhancement | "improve", "better", "update existing", "extend", incremental improvement |
      | refactor | "clean up", "simplify", "reorganize", "restructure" |
      | chore | "update deps", "upgrade", "maintenance", "CI/CD" |
      | documentation | "docs", "readme", "clarify", "examples" |

      Provide reasoning for your classification.
    depends_on: [fetch-issue]
    model: haiku
    allowed_tools: []
    output_format:
      type: object
      properties:
        issue_type:
          type: string
          enum: ["bug", "feature", "enhancement", "refactor", "chore", "documentation"]
        title:
          type: string
        reasoning:
          type: string
      required: [issue_type, title, reasoning]

  # ═══════════════════════════════════════════════════════════════
  # PHASE 2: RESEARCH (parallel with PR template fetch)
  # ═══════════════════════════════════════════════════════════════

  - id: web-research
    command: archon-web-research
    depends_on: [classify]
    context: fresh

  # ═══════════════════════════════════════════════════════════════
  # PHASE 3: INVESTIGATE (bugs) / PLAN (features)
  # ═══════════════════════════════════════════════════════════════

  - id: investigate
    command: archon-investigate-issue
    depends_on: [classify, web-research]
    when: "$classify.output.issue_type == 'bug'"
    context: fresh

  - id: plan
    command: archon-create-plan
    depends_on: [classify, web-research]
    when: "$classify.output.issue_type != 'bug'"
    context: fresh

  # Bridge: ensure investigation.md exists for the implement step
  # archon-fix-issue reads from $ARTIFACTS_DIR/investigation.md
  # archon-create-plan writes to $ARTIFACTS_DIR/plan.md
  # This node copies plan.md → investigation.md when the plan path was taken
  - id: bridge-artifacts
    bash: |
      if [ -f "$ARTIFACTS_DIR/plan.md" ] && [ ! -f "$ARTIFACTS_DIR/investigation.md" ]; then
        cp "$ARTIFACTS_DIR/plan.md" "$ARTIFACTS_DIR/investigation.md"
        echo "Bridged plan.md to investigation.md for implement step"
      elif [ -f "$ARTIFACTS_DIR/investigation.md" ]; then
        echo "investigation.md exists from investigate step"
      else
        echo "WARNING: No investigation.md or plan.md found — implement may fail"
      fi
    depends_on: [investigate, plan]
    trigger_rule: one_success

  # ═══════════════════════════════════════════════════════════════
  # PHASE 4: IMPLEMENT
  # ═══════════════════════════════════════════════════════════════

  - id: implement
    command: archon-fix-issue
    depends_on: [bridge-artifacts]
    context: fresh
    model: opus[1m]

  # ═══════════════════════════════════════════════════════════════
  # PHASE 5: VALIDATE
  # ═══════════════════════════════════════════════════════════════

  - id: validate
    command: archon-validate
    depends_on: [implement]
    context: fresh

  # ═══════════════════════════════════════════════════════════════
  # PHASE 6: CREATE DRAFT PR
  # ═══════════════════════════════════════════════════════════════

  - id: create-pr
    prompt: |
      Create a draft pull request for the current branch.

      ## Context

      - **Issue**: $ARGUMENTS
      - **Classification**: $classify.output
      - **Issue title**: $classify.output.title

      ## Instructions

      1. Check git status — ensure all changes are committed. If uncommitted changes exist, stage and commit them.
      2. Push the branch: \`git push -u origin HEAD\`
      3. Read implementation artifacts from \`$ARTIFACTS_DIR/\` for context:
         - \`$ARTIFACTS_DIR/investigation.md\` or \`$ARTIFACTS_DIR/plan.md\`
         - \`$ARTIFACTS_DIR/implementation.md\`
         - \`$ARTIFACTS_DIR/validation.md\`
      4. Check if a PR already exists for this branch: \`gh pr list --head $(git branch --show-current)\`
         - If PR exists, skip creation and capture its number
      5. Look for the project's PR template at \`.github/pull_request_template.md\`, \`.github/PULL_REQUEST_TEMPLATE.md\`, or \`docs/PULL_REQUEST_TEMPLATE.md\`. Read whichever one exists.
      6. Create a DRAFT PR: \`gh pr create --draft --base $BASE_BRANCH\`
         - Title: concise, imperative mood, under 70 chars
         - Body: if a PR template was found, fill in **every section** with details from the artifacts. Don't skip sections or leave placeholders. If no template, write a body with summary, changes, validation evidence, and \`Fixes #...\`.
         - Link to issue: include \`Fixes #...\` or \`Closes #...\`
      7. Capture PR identifiers:
         \`\`\`bash
         PR_NUMBER=$(gh pr view --json number -q '.number')
         echo "$PR_NUMBER" > "$ARTIFACTS_DIR/.pr-number"
         PR_URL=$(gh pr view --json url -q '.url')
         echo "$PR_URL" > "$ARTIFACTS_DIR/.pr-url"
         \`\`\`
    depends_on: [validate]
    context: fresh

  # ═══════════════════════════════════════════════════════════════
  # PHASE 7: REVIEW
  # ═══════════════════════════════════════════════════════════════

  - id: verify-pr-base
    bash: |
      set -euo pipefail
      EXPECTED="$BASE_BRANCH"
      ACTUAL=$(gh pr view --json baseRefName -q '.baseRefName')
      if [ "$ACTUAL" != "$EXPECTED" ]; then
        PR_NUMBER=$(gh pr view --json number -q '.number')
        echo "Base mismatch on PR #$PR_NUMBER: expected=$EXPECTED actual=$ACTUAL — re-targeting" >&2
        gh pr edit "$PR_NUMBER" --base "$EXPECTED"
      else
        echo "PR base verified: $EXPECTED"
      fi
    depends_on: [create-pr]

  - id: review-scope
    command: archon-pr-review-scope
    depends_on: [verify-pr-base]
    context: fresh

  - id: review-classify
    prompt: |
      You are a PR review classifier. Analyze the PR scope and determine
      which review agents should run.

      ## PR Scope

      $review-scope.output

      ## Rules

      - **Code review**: ALWAYS run. This is mandatory for every PR. It also checks
        the PR against CLAUDE.md rules and project conventions.
      - **Error handling**: Run if the diff touches code with try/catch, error handling,
        async/await, or adds new failure paths.
      - **Test coverage**: Run if the diff touches source code (not just tests, docs, or config).
      - **Comment quality**: Run if the diff adds or modifies comments, docstrings, JSDoc,
        or significant documentation within code files.
      - **Docs impact**: Run if the diff adds/removes/renames public APIs, commands, CLI flags,
        environment variables, or user-facing features.

      Provide your reasoning for each decision.
    depends_on: [review-scope]
    model: haiku
    allowed_tools: []
    context: fresh
    output_format:
      type: object
      properties:
        run_code_review:
          type: string
          enum: ["true", "false"]
        run_error_handling:
          type: string
          enum: ["true", "false"]
        run_test_coverage:
          type: string
          enum: ["true", "false"]
        run_comment_quality:
          type: string
          enum: ["true", "false"]
        run_docs_impact:
          type: string
          enum: ["true", "false"]
        reasoning:
          type: string
      required:
        - run_code_review
        - run_error_handling
        - run_test_coverage
        - run_comment_quality
        - run_docs_impact
        - reasoning

  # Code review always runs — mandatory
  - id: code-review
    command: archon-code-review-agent
    depends_on: [review-classify]
    context: fresh

  - id: error-handling
    command: archon-error-handling-agent
    depends_on: [review-classify]
    when: "$review-classify.output.run_error_handling == 'true'"
    context: fresh

  - id: test-coverage
    command: archon-test-coverage-agent
    depends_on: [review-classify]
    when: "$review-classify.output.run_test_coverage == 'true'"
    context: fresh

  - id: comment-quality
    command: archon-comment-quality-agent
    depends_on: [review-classify]
    when: "$review-classify.output.run_comment_quality == 'true'"
    context: fresh

  - id: docs-impact
    command: archon-docs-impact-agent
    depends_on: [review-classify]
    when: "$review-classify.output.run_docs_impact == 'true'"
    context: fresh

  # ═══════════════════════════════════════════════════════════════
  # PHASE 8: SYNTHESIZE + SELF-FIX
  # ═══════════════════════════════════════════════════════════════

  - id: synthesize
    command: archon-synthesize-review
    depends_on: [code-review, error-handling, test-coverage, comment-quality, docs-impact]
    trigger_rule: one_success
    context: fresh

  - id: self-fix
    command: archon-self-fix-all
    depends_on: [synthesize]
    context: fresh

  # ═══════════════════════════════════════════════════════════════
  # PHASE 9: SIMPLIFY
  # ═══════════════════════════════════════════════════════════════

  - id: simplify
    command: archon-simplify-changes
    depends_on: [self-fix]
    context: fresh

  # ═══════════════════════════════════════════════════════════════
  # PHASE 10: REPORT
  # ═══════════════════════════════════════════════════════════════

  - id: report
    command: archon-issue-completion-report
    depends_on: [simplify]
    context: fresh
`,
    'archon-test-loop-dag': `name: archon-test-loop-dag
description: |
  Use when: User explicitly says "test-loop-dag" or "run test-loop-dag".
  IMPORTANT: This is a DAG workflow with a loop node that iterates until completion.
  NOT for: General testing questions or debugging.
  Does: Initializes a counter, iterates until it reaches 3, then reports completion.

nodes:
  - id: setup
    bash: |
      echo "0" > .archon/test-loop-dag-counter.txt
      echo "Counter initialized to 0"

  - id: loop-counter
    depends_on: [setup]
    loop:
      prompt: |
        You are testing the loop node functionality within a DAG workflow.

        ## Your Task

        1. Read the file \`.archon/test-loop-dag-counter.txt\`
        2. Parse the current counter value
        3. Increment it by 1
        4. Write the new value back to the file
        5. Report the current iteration

        ## User Intent

        $USER_MESSAGE

        ## Completion Criteria

        - If the counter reaches 3 or higher, output: <promise>COMPLETE</promise>
        - Otherwise, just report your progress and end normally

        ## Important

        Be concise. Just do the task and report the counter value.
      until: COMPLETE
      max_iterations: 5
      fresh_context: false

  - id: report
    depends_on: [loop-counter]
    prompt: |
      The loop counter test has completed. The loop node output was:

      $loop-counter.output

      Read \`.archon/test-loop-dag-counter.txt\` and confirm the final counter value.
      Report: "Test loop DAG completed successfully. Final counter: {value}"
`,
  },
  patterns: {
    'classify-then-branch': `name: classify-then-branch
description: Classify input, branch on result.
nodes:
  - id: classify
    command: classify
  - id: branch-yes
    prompt: |
      $classify.output indicates yes — proceed with the affirmative path.
    depends_on: [classify]
    when: "$classify.output == 'yes'"
  - id: branch-no
    prompt: |
      $classify.output indicates no — handle the negative path.
    depends_on: [classify]
    when: "$classify.output == 'no'"
`,
    'fan-out-collect': `name: fan-out-collect
description: Three parallel workers feeding a single collector.
nodes:
  - id: dispatch
    command: dispatch-work
  - id: worker-a
    prompt: "Process slice A from $dispatch.output"
    depends_on: [dispatch]
  - id: worker-b
    prompt: "Process slice B from $dispatch.output"
    depends_on: [dispatch]
  - id: worker-c
    prompt: "Process slice C from $dispatch.output"
    depends_on: [dispatch]
  - id: collect
    prompt: |
      Combine results: $worker-a.output, $worker-b.output, $worker-c.output
    depends_on: [worker-a, worker-b, worker-c]
`,
    'loop-until-signal': `name: loop-until-signal
description: Loop with iteration cap that stops when AI output contains the completion signal.
nodes:
  - id: iterate
    loop:
      max_iterations: 5
      until: 'COMPLETE'
      prompt: |
        Make incremental progress on the task. When fully done, end your reply with the word COMPLETE.
  - id: followup
    prompt: |
      Summarise the result from $iterate.output.
    depends_on: [iterate]
`,
  },
} as const;
