/**
 * Inline snippet YAMLs into a TS module so studio-core consumers don't pull in
 * Node fs at runtime. The browser bundle (Vite, standalone shell) imports
 * `loadSnippet` from @archon-studio/fixtures, which now resolves a static map
 * built at this file's compile-time.
 *
 * Re-run via `bun run build-snippet-data` whenever the YAML sources change.
 * The generated output is committed (not gitignored) so consumers don't need
 * to run a build step before importing.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const base = join(root, 'packages/studio-fixtures/src/snippets');

const starters = ['archon-feature-development', 'archon-fix-github-issue', 'archon-test-loop-dag'];
const patterns = ['classify-then-branch', 'fan-out-collect', 'loop-until-signal'];

function escapeBacktick(s: string): string {
  // For a template literal we must escape: backslash, backtick, and `${`.
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

let out = '// AUTO-GENERATED by scripts/build-snippet-data.ts. Do not edit by hand.\n';
out += '// Source files: packages/studio-fixtures/src/snippets/{starters,patterns}/*.yaml\n';
out += '// Inlined so studio-core consumers (Vite browser bundle) avoid runtime node:fs.\n\n';
out += 'export const SNIPPET_DATA = {\n  starters: {\n';
for (const n of starters) {
  const yaml = readFileSync(join(base, 'starters', `${n}.yaml`), 'utf8');
  out += `    ${JSON.stringify(n)}: \`${escapeBacktick(yaml)}\`,\n`;
}
out += '  },\n  patterns: {\n';
for (const n of patterns) {
  const yaml = readFileSync(join(base, 'patterns', `${n}.yaml`), 'utf8');
  out += `    ${JSON.stringify(n)}: \`${escapeBacktick(yaml)}\`,\n`;
}
out += '  },\n} as const;\n';

const outPath = join(root, 'packages/studio-fixtures/src/snippet-data.generated.ts');
writeFileSync(outPath, out);
console.log(`Wrote ${outPath} (${out.length} bytes)`);
